- platform: template
  switches:
    light_bowl:
      value_template: "{{ is_state('switch.light_bowl', 'on') }}"
      turn_on:
        service: remote.send_command
        entity_id: remote.living_room
        data: 
          entity_id: remote.living_room
          device: 56026507
          command: PowerOn
      turn_off:
        service: remote.send_command
        entity_id: remote.living_room
        data: 
          entity_id: remote.living_room
          device: 56026507
          command: PowerOff
    light_christmas:
      value_template: "{{ is_state('switch.light_christmas', 'on') }}"
      turn_on:
        service: remote.send_command
        entity_id: remote.living_room
        data: 
          entity_id: remote.living_room
          device: 59413425
          command: PowerOn
      turn_off:
        service: remote.send_command
        entity_id: remote.living_room
        data: 
          entity_id: remote.living_room
          device: 59413425
          command: PowerOff
