- alias: Set Viera volume
  trigger:
  - entity_id: input_number.slider_viera_volume
    platform: state
  action:
  - service: media_player.volume_set
    entity_id: media_player.viera
    data_template:
      volume_level: '{{ states(''input_number.slider_viera_volume'') | float }}

        '
- action:
  - service: group.set_visibility
    entity_id: group.living_room_helpers
    data:
      visible: true
  alias: Viera on
  id: '1515235740228'
  trigger:
  - entity_id: media_player.viera
    platform: state
    to: 'on'
- action:
  - service: group.set_visibility
    entity_id: group.living_room_helpers
    data:
      visible: false
  alias: Viera off
  id: '1515235740229'
  trigger:
  - entity_id: media_player.viera
    platform: state
    to: 'off'

#- action:
#  - service: shell_command.restart_wifi
#  alias: restart_wifi
#  trigger:
#  - platform: state
#    entity_id: binary_sensor.wifi 
#    to: 'off' 
