- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_off
  alias: MQTT Shield off
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'on'
  id: '1519561541052'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_on
  alias: MQTT Shield on
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'off'
  id: '1519561583777'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'on'
