#- alias: Set Viera volume
#  trigger:
#  - entity_id: input_number.slider_viera_volume
#    platform: state
#  action:
#  - service: media_player.volume_set
#    entity_id: media_player.viera
#    data_template:
#      volume_level: '{{ states(''input_number.slider_viera_volume'') | float }}
#
#        '
#- action:
#    service: group.set_visibility
#    data:
#      entity_id: group.living_room_helpers
#      visible: true
#  alias: Viera on
#  id: '1515235740228'
#  trigger:
#  - entity_id: media_player.viera
#    platform: state
#    to: 'on'
#- action:
#    service: group.set_visibility
#    data:
#      entity_id: group.living_room_helpers
#      visible: false
#  alias: Viera off
#  id: '1515235740229'
#  trigger:
#  - entity_id: media_player.viera
#    platform: state
#    to: 'off'
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_on
  alias: Shield on
  id: '1517123273109'
  trigger:
  - entity_id: binary_sensor.shield_power
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'off'
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_off
  id: '1517754543109'
  trigger:
  - entity_id: binary_sensor.shield_power
    platform: state
    to: 'off'
  alias: Shield off
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'on'
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat
    service: climate.set_operation_mode
  alias: Heat 06:00 Auto up
  id: '1517769273109'
  trigger:
  - at: 06:00
    platform: time
  condition:
  - condition: state
    entity_id: input_select.heat
    state: Auto
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat 22:00 not home down
  condition:
  - condition: state
    entity_id: group.people
    state: not_home
  id: '1517769647601'
  trigger:
  - at: '22:00'
    platform: time
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat
    service: climate.set_operation_mode
  alias: Heat 08:00 - 16:30 Auto up
  condition:
  - after: 08:00
    before: '16:30'
    condition: time
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  - condition: state
    entity_id: input_select.heat
    state: Auto
  id: '1519219045865'
  trigger:
  - entity_id: group.people
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat 08:00 - 16:30 Auto down
  condition:
  - after: 08:00
    before: '16:30'
    condition: time
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  - condition: state
    entity_id: input_select.heat
    state: Auto
  id: '1519219194083'
  trigger:
  - entity_id: group.people
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat 24:00 down
  condition: []
  id: '1519219354612'
  trigger:
  - at: 00:00
    platform: time
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat 08:00 Auto week down
  condition:
  - condition: state
    entity_id: group.people
    state: not_home
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  - condition: state
    entity_id: input_select.heat
    state: Auto
  id: '1519220863285'
  trigger:
  - at: 08:00
    platform: time
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat
    service: climate.set_operation_mode
  alias: Heat 16:30 Auto week up
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  - condition: state
    entity_id: input_select.heat
    state: Auto
  id: '1519225405230'
  trigger:
  - at: '16:30'
    platform: time
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat
    service: climate.set_operation_mode
  alias: Heat 06:00 On up
  condition:
  - condition: state
    entity_id: input_select.heat
    state: 'on'
  id: '1519225819175'
  trigger:
  - at: 06:00
    platform: time
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat to Off
  condition: []
  id: '1519226982225'
  trigger:
  - entity_id: input_select.heat
    platform: state
    to: 'Off'
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat
    service: climate.set_operation_mode
  alias: Heat to On
  condition: []
  id: '1519227023922'
  trigger:
  - entity_id: input_select.heat
    platform: state
    to: 'On'
- action:
  - data:
      entity_id: climate.termohlava_dry_air
      operation_mode: Heat Econ
    service: climate.set_operation_mode
  alias: Heat 22:00 - 24:00 not home down
  condition:
  - after: '22:00'
    before: 00:00
    condition: time
  id: '1519227677584'
  trigger:
  - entity_id: group.people
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_off
  alias: MQTT Shield off
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'on'
  id: '1519561541052'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_on
  alias: MQTT Shield on
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'off'
  id: '1519561583777'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'on'
