- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_off
  initial_state: true 
  alias: MQTT Shield off
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'on'
  id: '1519561541052'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: switch.switch3
    service: switch.turn_on
  initial_state: true 
  alias: MQTT Shield on
  condition:
  - condition: state
    entity_id: switch.switch3
    state: 'off'
  id: '1519561583777'
  trigger:
  - entity_id: binary_sensor.shield_power_mqtt
    platform: state
    to: 'on'
- id: '1551386746983'
  initial_state: true 
  alias: 'Presence Peto Wifi - to home'
  trigger:
  - entity_id: device_tracker.presence_peto
    platform: state
    to: 'home'
  action:
  - data:
      entity_id: input_select.presence_peto_wifi
      option: 'home'
    service: input_select.select_option
- id: '1551386850844'
  initial_state: true 
  alias: 'Presence Peto Wifi - to not_home'
  trigger:
  - entity_id: device_tracker.presence_peto
    platform: state
    to: 'not_home'
  action:
  - data:
      entity_id: input_select.presence_peto_wifi
      option: 'not_home'
    service: input_select.select_option
- id: '1551386998548'
  initial_state: true 
  alias: 'Presence Nikik Wifi - to home'
  trigger:
  - entity_id: device_tracker.presence_nikik
    platform: state
    to: 'home'
  action:
  - data:
      entity_id: input_select.presence_nikik_wifi
      option: 'home'
    service: input_select.select_option
- id: '1551387048129'
  initial_state: true 
  alias: 'Presence Nikik Wifi - to not home'
  trigger:
  - entity_id: device_tracker.presence_nikik
    platform: state
    to: 'not_home'
  action:
  - data:
      entity_id: input_select.presence_nikik_wifi
      option: 'not_home'
    service: input_select.select_option
