homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.10226
  longitude: 17.09939
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 140
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Bratislava
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

recorder:
  purge_interval: 1 
  purge_keep_days: 2 
  exclude:
    entities:
      - group.status
      - group.people3
      - input_boolean.notify_home
      - automation.run_set_viera_volume
      - automation.set_viera_volume
      - group.people_grp
      - group.people2

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - input_boolean.notify_home
      - group.status
      - group.status_view
      - group.people3
      - group.people_grp
      - group.people2
      - group.default_view
      - group.living_room
      - group.all_automations
      - group.people_view
      - group.living_room_helpers
      - automation.run_set_viera_volume
      - automation.set_viera_volume
      - automation.viera_on
      - automation.viera_off
      - automation.new_automation
      - automation.viera_volume_visible
      - automation.set_viera_volume_visible

# Discover some devices automatically
discovery:
  ignore:
    # set below with proper naming
    - panasonic_viera
    - google_cast
      #    - spotify_connect # unknown value

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
# PSPS - len pre alexu, resp. ineho voice asistenta?
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
device_tracker: !include_dir_merge_list device_trackers/
media_player: !include_dir_merge_list media_players/

notify:
  - platform: nfandroidtv
    name: ShieldTV
    host: 192.168.1.4
    
# nemalo by byt treba - malo by stacit panasonic_viera, podla vsetkeho nefunguje WOL na europskych modeloch TV >:-(
#switch:
#  - platform: wake_on_lan
#    name: televiziaWOL
#    host: 192.168.1.7
#    mac_address: "c0-d9-62-f6-c3-5b

input_number:
  slider_viera_volume:
    name: Volume
    initial: 0.25
    min: 0
    max: 1
    step: 0.01
    mode: box
#    unit_of_measurement: "%" # robi groupovanie so Synology volume
