homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.10226
  longitude: 17.09939
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 140
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Bratislava
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

recorder:
  exclude:
    entities:
      - group.status
      - group.people3
      - input_boolean.notify_home
      - automation.run_set_viera_volume
      - group.people_grp
      - group.people2

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - group.status
      - group.status_view
      - group.people3
      - input_boolean.notify_home
      - automation.run_set_viera_volume
      - group.people_grp
      - group.people2
      - group.default_view
      - group.living_room
      - group.all_automations
      - automation.set_viera_volume
      - group.people_view

        # Discover some devices automatically
discovery:
  ignore:
    # set below with proper naming
    - panasonic_viera
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
# PSPS - len pre alexu, resp. ineho voice asistenta?
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sensor:
  - platform: yr
  - platform: synologydsm
    host: 192.168.1.10
    port: 8080
    name: PornoNAS
    username: !secret pornonas_username
    password: !secret pornonas_password
    volumes: 
      - volume_1
    disks:
      - sda
      - sdb
    monitored_conditions:
      - disk_temp
      - volume_percentage_used
#      - cpu_total_load

binary_sensor:
  - platform: command_line
    name: Wifi
    # raz denne sa spusta job na routeri, ktori reinitializuje wifi tak, aby sa vypla izolacia na wifi a arp prechadzali
    command: /home/homeassistant/.homeassistant/scripts/wifi_check_reinit.sh 192.168.1.6 2>&1 | tee -a /home/homeassistant/.homeassistant/scripts/wifi_check_reinit.log
    device_class: connectivity
    payload_on: OK
    payload_off: FAIL
    scan_interval: 60

device_tracker:
  - platform: luci
    host: 192.168.1.1
    username: root
    password: !secret router_password
    name: Router
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

media_player:
  - platform: panasonic_viera
    host: 192.168.1.7
    name: Viera
    mac: "c0:d9:62:f6:c3:5b"
  - platform: cast
    # v customize.yaml premenovane na shield
    host: 192.168.1.4
#  - platform: kodi
#    host: 192.168.1.4
#    name: Kodi
#    username: kodi
#    enable_websocket: false
#  - platform: spotify
#    client_id: <your client id>
#    client_secret: <your client secret>
#    aliases:
#      abc123def456: 'Living Room'
#      9183abas000: 'Bed Room'

notify:
  - platform: nfandroidtv
    name: ShieldTV
    host: 192.168.1.4
    
# nemalo by byt treba - malo by stacit panasonic_viera, podla vsetkeho nefunguje WOL na europskych modeloch TV >:-(
#switch:
#  - platform: wake_on_lan
#    name: televiziaWOL
#    host: 192.168.1.7
#    mac_address: "c0-d9-62-f6-c3-5b

input_number:
  slider_viera_volume:
    name: Volume
    initial: 0.25
    min: 0
    max: 1
    step: 0.01
    mode: box
    #    unit_of_measurement: "%" # robi groupovanie so Synology volume
