homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.10226
  longitude: 17.09939
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 140
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Bratislava
  whitelist_external_dirs:
    - /shared
  # Customization file
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
      - 127.0.0.1
      - 192.168.1.0/24
      - 172.17.0.0/16
      - 172.16.0.0/16
    - type: legacy_api_password
      api_password: !secret api_password
# Show links to resources in log and frontend
#introduction:

logger:
  default: info
  logs:
    homeassistant.components.device_tracker: debug
    homeassistant.components.http.view: warn
    homeassistant.components.websocket_api.http.connection: info

system_health:
    
# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  base_url: http://nuc.local:8123
  #base_url: https://nuc.local:8123
  #ssl_certificate: /config/certificate.pem
  #ssl_key: /config/certificate.key
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.

zone:
  - name: Work
    latitude: 48.157588
    longitude: 17.1289508
    icon: mdi:worker

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
#  include_used_components: true

prometheus:
# nefunguje dobre, nie vsetky informacie su posielane -> chyba komponentu

recorder:
  purge_interval: 1 
  purge_keep_days: 2 
#  exclude:
#    entities:
#      - automation.set_viera_volume

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - group.default_view
      - group.people_view
      - group.nas_status_view
      - group.presence_peto
      - group.presence_custom
      - group.entertainment
      - group.thermostat
      - group.nas_status
      - group.weather_temperature
      - group.weather_humidity
      - group.weather_wind
      - group.weather_pressure
      - group.weather_precipation
      - group.weather_view
      - persistent_notification.invalid_config

# Discover some devices automatically
discovery:
  ignore:
    - google_cast
    - panasonic_viera
#  enable:
#    - dlna_dmr

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.5

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    base_url: http://192.168.1.6:8123

# Cloud
# PSPS - len pre alexu, resp. ineho voice asistenta?
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
device_tracker: !include_dir_merge_list device_trackers/
media_player: !include_dir_merge_list media_players/
switch: !include_dir_merge_list switches/

plant:
  plant1:
    sensors:
      moisture: sensor.miflora1_moisture
      battery: sensor.miflora1_battery
      temperature: sensor.miflora1_temperature
      conductivity: sensor.miflora1_conductivity
      brightness: sensor.miflora1_brightness
  plant2:
    sensors:
      moisture: sensor.miflora2_moisture
      battery: sensor.miflora2_battery
      temperature: sensor.miflora2_temperature
      conductivity: sensor.miflora2_conductivity
      brightness: sensor.miflora2_brightness
  plant3:
    sensors:
      moisture: sensor.miflora3_moisture
      battery: sensor.miflora3_battery
      temperature: sensor.miflora3_temperature
      conductivity: sensor.miflora3_conductivity
      brightness: sensor.miflora3_brightness
  plant4:
    sensors:
      moisture: sensor.miflora4_moisture
      battery: sensor.miflora4_battery
      temperature: sensor.miflora4_temperature
      conductivity: sensor.miflora4_conductivity
      brightness: sensor.miflora4_brightness

#zwave:
## ls -ltr /dev/tty*|tail -n 1
  #  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  ##  usb_path: /dev/ttyUSB0
#  config_path: /config/open-zwave/config
#  network_key: "0x22, 0x50, 0xA1, 0xBC, 0x62, 0x87, 0xBD, 0x00, 0xFC, 0x9D, 0x5C, 0xCC, 0xAC, 0xA8, 0x2D, 0xFA"
#  device_config: !include zwave_device_config.yaml

#notify:
#  - platform: nfandroidtv
#    name: ShieldTV
#    host: 192.168.1.4
    
# nemalo by byt treba - malo by stacit panasonic_viera, podla vsetkeho nefunguje WOL na europskych modeloch TV >:-(
#switch:
#  - platform: wake_on_lan
#    name: televiziaWOL
#    host: 192.168.1.7
#    mac_address: "c0-d9-62-f6-c3-5b

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml

input_text:
  tts_input:
    name: Text
    
ffmpeg:

stream:    
#  extra_arguments: -bsf:v h264_mp4toannexb

camera:
  - platform: local_file
    file_path: /config/empty.jpg
    name: Google Photos
  # funguje
#  - platform: ffmpeg
#    input: !secret camera_ffmpeg_rtmp
#    name: C1pro-ffmpeg-rtmp
#    #extra_arguments: -q:v 2
#    extra_arguments: -pred 1
#  # funguje    
#  - platform: ffmpeg
#    input: !secret camera_ffmpeg_rtsp
#    name: C1pro-ffmpeg-rtsp
#    #extra_arguments: -q:v 2
#    extra_arguments: -pred 1
  - platform: generic
    still_image_url: !secret camera_generic
    stream_source: !secret camera_generic_stream
    name: C1pro-generic
# 400 - bad request! Unauthorized -> potrebna zmena onvif.py (existuje PR)
#  - platform: onvif
#    host: 192.168.1.253
#    name: C1pro-onvif
#    username: !secret camera_username
#    password: !secret camera_password
#    port: 8000
#    profile: 0
#  - platform: mjpeg
#    mjpeg_url: http://192.168.1.36:2971/camera/stream
#    name: WallPanel Camera

#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.C1pro-generic
# - platform: dlib_face_identify
#   source:
#    - entity_id: camera.C1pro-generic
#   faces:
#     Nikik: www/nikik.jpg
#     Peto: www/peto.jpg

tplink:
  discovery: false
  switch:
    - host: 192.168.3.101
    - host: 192.168.3.102
    - host: 192.168.3.103

#shell_command:
#  restart_wifi: ssh root@192.168.1.1 -p 2222 wifi

#android_ip_webcam:
#  - host: 192.168.1.69
#    name: wildfires
#    sensors:
#      - light
#    switches:
#      - torch
#      - video_recording

#mqtt:
#  broker: 192.168.1.6
#  port: 1883
#  discovery: true
#  discovery_prefix: hass

climate:
- platform: climate_ip
  config_file: 'samsungrac.yaml'
  ip_address: '192.168.1.250'
  token: '3E29WItMSX'
  cert: 'ac14k_m.pem'
  name: AC
  debug: false
  poll: true

weather:
  - platform: darksky
    api_key: ade4656f857c75c148f280af97652fa7
    units: si
#    mode: daily

#speedtestdotnet:
#  server_id: 3902
#  monitored_conditions:
#    - ping
#    - download
#    - upload

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 698188355
      - -262852350

# Example configuration.yaml entry for the notifier
notify:
  - name: peto_telegram
    platform: telegram
    chat_id: 698188355
