sensor.termohlava_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.termohlava_alarm_type:
  ignored: true
  polling_intensity: 0
climate.termohlava_cooling_1:
  ignored: true
  polling_intensity: 0
sensor.termohlava_power_management:
  ignored: true
  polling_intensity: 0
sensor.termohlava_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.termohlava_system:
  ignored: true
  polling_intensity: 0
sensor.termohlava_temperature:
  ignored: false
  polling_intensity: 300
