- platform: synologydsm
  host: 192.168.1.10
  name: PornoNAS
  port: 8080
  ssl: false
  username: !secret pornonas_username
  password: !secret pornonas_password
  volumes:
  - volume_1
  disks:
  - sda
  - sdb
  monitored_conditions:
  - disk_temp
  - volume_percentage_used
