- platform: template
  sensors:
    yr_wind_speed_kph:
      friendly_name: "yr Wind speed"
      unit_of_measurement: 'kph'
      entity_id: sensor.yr_wind_speed 
      value_template: "{{ ( states('sensor.yr_wind_speed') | float * 3600 / 1000 ) | int }}"
      icon_template: mdi:weather-windy
    presence_peto:
      value_template: '{{ states.input_select.presence_peto.state }}'
      friendly_name: 'Peto'
    presence_nikik:
      value_template: '{{ states.input_select.presence_nikik.state }}'
      friendly_name: 'Nikik'      
