- platform: template
  sensors:
    yr_wind_speed_kph:
      friendly_name: "yr Wind speed"
      unit_of_measurement: 'kph'
      entity_id: sensor.yr_wind_speed 
      value_template: "{{ ( states('sensor.yr_wind_speed') | float * 3600 / 1000 ) | int }}"
      icon_template: mdi:weather-windy
    presence_peto:
      value_template: '{{ states.input_select.presence_peto.state }}'
      friendly_name: 'Peto'
      icon_template: >-
        {% if is_state('input_select.presence_peto', 'Home') %}
          mdi:home-account
        {% elif is_state('input_select.presence_peto', 'Away') %}
          mdi:image-filter-hdr
        {% elif is_state('input_select.presence_peto', 'Asleep') %}
          mdi:sleep
        {% elif is_state('input_select.presence_peto', 'Extended Away') %}
          mdi:briefcase
        {% endif %}
    presence_nikik:
      value_template: '{{ states.input_select.presence_nikik.state }}'
      friendly_name: 'Nikik'      
      icon_template: >-
        {% if is_state('input_select.presence_nikik', 'Home') %}
          mdi:home-account
        {% elif is_state('input_select.presence_nikik', 'Away') %}
          mdi:image-filter-hdr
        {% elif is_state('input_select.presence_nikik', 'Asleep') %}
          mdi:sleep
        {% elif is_state('input_select.presence_nikik', 'Extended Away') %}
          mdi:briefcase
        {% endif %}
    presence:
      icon_template: mdi:account-group
      value_template: '{{ states.input_select.presence.state }}'
      friendly_name: 'People'      
    presence_peto_ble_friendly:
      friendly_name: 'Peto BLE'
      value_template: >-
        {% if is_state('sensor.presence_peto_ble', 'not_home') %}
          Not home
        {% else %}
          {{ states('sensor.presence_peto_ble') }}
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.presence_peto_ble', 'not_home') %}
          mdi:bluetooth-off
        {% else %}
          mdi:bluetooth-connect
        {% endif %}
    presence_nikik_ble_friendly:
      friendly_name: 'Nikik BLE'
      value_template: >-
        {% if is_state('sensor.presence_nikik_ble', 'not_home') %}
          Not home
        {% else %}
          {{ states('sensor.presence_nikik_ble') }}
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.presence_nikik_ble', 'not_home') %}
          mdi:bluetooth-off
        {% else %}
          mdi:bluetooth-connect
        {% endif %}
    presence_peto_wifi:
      friendly_name: 'Peto Wifi'
      value_template: >-
        {% if is_state('input_select.presence_peto_wifi', 'home') %}
          Connected
        {% else %}
          Not connected
        {% endif %}
      icon_template: >-
        {% if is_state('input_select.presence_peto_wifi', 'home') %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}
    presence_nikik_wifi:
      friendly_name: 'Nikik Wifi'
      value_template: >-
        {% if is_state('input_select.presence_nikik_wifi', 'home') %}
          Connected
        {% else %}
          Not connected
        {% endif %}
      icon_template: >-
        {% if is_state('input_select.presence_nikik_wifi', 'home') %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}
    camera_mode_is_baby_monitor:
      entity_id: input_select.camera_mode
      value_template: >-
        {% if is_state('input_select.camera_mode', 'Baby monitor') %}
          on
        {% else %}
          off
        {% endif %}
#    camera_mode:
#      friendly_name: 'Camera Mode'
#      entity_id: input_select.camera_mode
#      value_template: '{{ states.input_select.camera_mode.state }}'
#      icon_template: >-
#        {% if is_state('input_select.camera_mode', 'Timelapse') %}
#          mdi:cctv
#        {% elif is_state('input_select.camera_mode', 'Off') %}
#          mdi:close-circle-outline
#        {% else %}
#          mdi:baby
#        {% endif %}
    googlesk_ping:
      value_template: "{{ state_attr('binary_sensor.googlesk_ping', 'round_trip_time_avg') }}"
      unit_of_measurement: 'ms'
    googlecom_ping:
      value_template: "{{ state_attr('binary_sensor.googlecom_ping', 'round_trip_time_avg') }}"
      unit_of_measurement: 'ms'
    facebook_ping:
      value_template: "{{ state_attr('binary_sensor.facebook_ping', 'round_trip_time_avg') }}"
      unit_of_measurement: 'ms'
    livingroom_hotness:
      value_template: >-
        {% if states('sensor.oko_temperature_2')|float > states('input_number.ok_upper_treshold')|float %}
          hot
        {% elif states('sensor.oko_temperature_2')|float > states('input_number.ok_lower_treshold')|float %}
          ok
        {% else %}
          cold
        {% endif %}
      icon_template: mdi:fire
    outside_hotness:
      value_template: >-
        {% if states('sensor.yr_temperature')|float > states('input_number.ok_upper_treshold')|float %}
          hot
        {% elif states('sensor.dark_sky_temperature')|float > states('input_number.ok_upper_treshold')|float %}
          hot
        {% elif states('sensor.yr_temperature')|float > states('input_number.ok_lower_treshold')|float %}
          ok
        {% elif states('sensor.dark_sky_temperature')|float > states('input_number.ok_lower_treshold')|float %}
          ok
        {% else %}
          cold
        {% endif %}
      icon_template: mdi:fire
