- platform: template
  sensors:
    yr_wind_speed_kph:
      friendly_name: "yr Wind speed"
      unit_of_measurement: 'kph'
      entity_id: sensor.yr_wind_speed 
      value_template: "{{ ( states('sensor.yr_wind_speed') | float * 3600 / 1000 ) | int }}"
      icon_template: mdi:weather-windy
