- platform: template
  sensors:
    switch1_consumption:
# 0.60.1
#      value_template: '{{states.switch.switch1.attributes["current_consumption"] | replace(" W", "") | float}}'
# 0.61.1
      value_template: '{{states.switch.switch1.attributes["current_power_w"] | replace(" W", "") | float}}'
      unit_of_measurement: 'W'
