#- platform: command_line
#  name: Shield Power
#  command: /config/shell_scripts/shield_tv_check.sh 192.168.1.4 2>&1 | tee -a /config/shell_scripts/shield_tv_check.log
#  payload_on: OK
#  payload_off: FAIL
#  scan_interval: 20
- platform: mqtt
  name: "Shield Power MQTT"
  state_topic: "hass/shield/state"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 0
