- platform: command_line
  name: Wifi
  # raz denne sa spusta job na routeri, ktori reinitializuje wifi tak, aby sa vypla izolacia na wifi a arp prechadzali
  command: /home/homeassistant/.homeassistant/scripts/wifi_check_reinit.sh 192.168.1.6 2>&1 | tee -a /home/homeassistant/.homeassistant/scripts/wifi_check_reinit.log
  device_class: connectivity
  payload_on: OK
  payload_off: FAIL
  scan_interval: 60
