- platform: luci
  host: 192.168.11.10
  username: root
  password: !secret router_password
  name: Router
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False
                                            
